name = "ShortStrings"
uuid = "63221d1c-8677-4ff0-9126-0ff0817b4975"
authors = ["Dai ZJ <zhuojia.dai@gmail.com>"]
version = "0.2.0"

[deps]
SortingAlgorithms = "a2af1166-a08f-5f64-846c-94a0d3cef48c"

[compat]
SortingAlgorithms = "0.3"
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
